- name: Restore service files
  environment:
    BORG_RSH: "{{ BORG_RSH }}"
    BORG_REPO: "{{ BORG_REPO }}"
    BORG_PASSPHRASE: "{{ BORG_PASSPHRASE }}"
  shell:
    cmd: "borg extract --strip-components 3 -v --list {{ BORG_REPO }}::{{ VERSION }} /etc/systemd/system/"
    chdir: "/etc/systemd/system"
  async: 3600
  poll: 10