- name: Samba
  block:
    - name: Change the file permissions for samba
      file:
        path: "{{ sambaconfigfolder }}"
        state: directory
        recurse: yes
        owner: root
        group: root
        mode: '0755'

    - name: Clear the samba config folder - {{ sambaconfigfolder }}
      shell: "rm -rf {{ sambaconfigfolder }}/*"

    - name: Restore samba config folder - {{ sambaconfigfolder }}
      environment:
        BORG_RSH: "{{ BORG_RSH }}"
        BORG_REPO: "{{ BORG_REPO }}"
        BORG_PASSPHRASE: "{{ BORG_PASSPHRASE }}"
      shell:
        cmd: "borg extract --strip-components 2 -v --list {{ BORG_REPO }}::{{ VERSION }} {{ sambaconfigfolder }}"
        chdir: "{{ sambaconfigfolder }}"
      async: 3600
      poll: 10

    - name: Restart samba
      systemd:
        name: smbd
        state: restarted