- name: Caddy
  block:
    - name: Clear previous files
      shell: rm -rf /etc/caddy/*

    - name: Pull caddy files from backup
      environment:
        BORG_RSH: "{{ BORG_RSH }}"
        BORG_REPO: "{{ BORG_REPO }}"
        BORG_PASSPHRASE: "{{ BORG_PASSPHRASE }}"
      shell:
        cmd: "borg extract --strip-components 2 -v --list {{ BORG_REPO }}::{{ VERSION }} {{ caddyfolder }}"
        chdir: "{{ caddyfolder }}"
      async: 3600
      poll: 10

    - name: Change permissions to root
      file:
        path: "{{ caddyfolder }}"
        state: directory
        recurse: yes
        owner: root
        group: root

    - name: Restart caddy
      service:
        name: caddy
        state: restarted