- name: Download and install scripts
  block:
    - name: Make sure the scripts folder exists - {{ scriptsfolder }}
      file: 
        path: "{{ scriptsfolder }}"
        state: directory
        mode: '0755'

    - name: Clear the scripts folder - {{ scriptsfolder }}
      shell: "rm -rf {{ scriptsfolder }}/*"

    - name: Restore scripts folder - {{ scriptsfolder }}
      environment:
        BORG_RSH: "{{ BORG_RSH }}"
        BORG_REPO: "{{ BORG_REPO }}"
        BORG_PASSPHRASE: "{{ BORG_PASSPHRASE }}"
      shell:
        cmd: "borg extract --strip-components 2 -v --list {{ BORG_REPO }}::{{ VERSION }} {{ scriptsfolder }}"
        chdir: "{{ scriptsfolder }}"
      async: 3600
      poll: 10