VERSION: 2025-11-11_20:11
websitefolder: /var/www/html
scriptsfolder: /etc/scripts
sambaconfigfolder: /etc/samba
caddyfolder: /etc/caddy
wireguardconfig: /etc/wireguard
users_with_home:
  - jan
users_no_home:
  - mathijs
  - ignas
  - steam
  - dockeruser
samba_users:
  - jan
  - ignas
containers:
  - dockge
packages:
  - sudo
  - ca-certificates
  - curl
  - rsync
  - borgbackup
  - cockpit
  - caddy
  - netfilter-persistent
  - iptables
  - samba
  - vim
  - ncdu
  - ssh
  - tree